### ISSUE TITLE
Cannot create domain using the custom PddlDomain class

### ISSUE THREAD

**Issue by francescobozzo** [unitn-ASA/Deliveroo.js#1]
## Issue

Dear professor,

Currently, when instantiating a new pddl domain by using `PddlDomain`, predicates are automatically inferred from preconditions and effects when parsing the given actions with this line of code:

https://github.com/unitn-ASA/Deliveroo.js/blob/df18cdf00e2bccd69be5b327545b64db96b736b3/packages/%40unitn-asa/pddl-client/src/PddlDomain.js#L50

The issue is that the following exception is thrown also when we don't have any duplicate predicates:
https://github.com/unitn-ASA/Deliveroo.js/blob/df18cdf00e2bccd69be5b327545b64db96b736b3/packages/%40unitn-asa/pddl-client/src/PddlDomain.js#L30-L31

Example of an action that will raise the exception:
```pddl
(:action example
    :parameters (?param1)
    :precondition (and (light ?l) (light ?l-with-different-len))
    ....
)
```

In this case here is the course of action:
1. `light ?l` is inserted correctly in the predicate list;
2.  when trying to add `light ?l-with-different-len`:
  1. `e.split(' ')[0] == predicate.split(' ')[0]` succeeds;
  2. but `e.length != predicate.length` is also true since `'light ?l'.length != 'light ?l-with-different-len'.length`. Therefore the exception is thrown.

## Proposed solution

Instead of string lengths, we should check if the **number of arguments of the predicate** matches. Something like:
```js
this.predicates.find( (e) => e.split(' ')[0] == predicate.split(' ')[0] && e.split(' ').length != predicate.split(' ').length )
```

**Comment by francescobozzo** [comment]
Please, consider also:

https://github.com/unitn-ASA/Deliveroo.js/blob/df18cdf00e2bccd69be5b327545b64db96b736b3/packages/%40unitn-asa/pddl-client/src/PddlDomain.js#L32

If I am not wrong, this operation should be performed only a single time for each predicate with the same name. Therefore, if we find both `(light ?l) (light ?l-with-different-len)` the push action should be executed only when processing the first predicate.

**Comment by marcorobol** [comment]
Thank you Francesco, this seems reasonable. I think my initial idea was use _length_ to count the numbers of arguments, probably I used it wrongly so that I'm counting the numbers of chars. Definitely to be fixed.
